"""oracle core domain

Revision ID: 20260710_0004
Revises: 20260710_0003
Create Date: 2026-07-10 14:39:10.089255
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260710_0004"
down_revision: str | None = "20260710_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN IF current_user <> 'oracle_migrator' THEN RAISE EXCEPTION 'phase 06 migrations require oracle_migrator'; END IF; END $$"
    )
    op.create_unique_constraint("uq_workspaces_id_tenant", "workspaces", ["id", "tenant_id"])
    op.execute("""
      INSERT INTO permissions(key,description) VALUES
      ('dossier.archive','Archivar expedientes sin borrado físico.'),('signal.read','Consultar señales.'),
      ('signal.promote','Promover señales.'),('opportunity.read','Consultar oportunidades.'),
      ('opportunity.write','Gestionar oportunidades.'),('risk.read','Consultar riesgos.'),
      ('risk.write','Gestionar riesgos.'),('actor.read','Consultar actores.'),
      ('actor.write','Gestionar actores.'),('meeting.read','Consultar reuniones.'),
      ('meeting.write','Gestionar reuniones.'),('report.read','Consultar informes.'),
      ('task.read','Consultar tareas.'),('task.write','Gestionar tareas.')
      ON CONFLICT(key) DO UPDATE SET description=EXCLUDED.description
    """)
    op.create_table(
        "actors",
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("canonical_key", sa.String(length=320), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("identifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_actors_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_actors_id_tenant"),
        sa.UniqueConstraint("tenant_id", "canonical_key", name="uq_actor_canonical_key"),
    )
    op.create_index(
        "ix_actors_tenant_name", "actors", ["tenant_id", "canonical_name"], unique=False
    )
    op.create_table(
        "ai_audit_logs",
        sa.Column("dossier_id", sa.UUID(), nullable=True),
        sa.Column("use_case", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=150), nullable=False),
        sa.Column("prompt_name", sa.String(length=150), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("input_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("output_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("source_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_micros", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_audit_logs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_audit_logs")),
    )
    op.create_index(
        "ix_ai_audit_tenant_dossier",
        "ai_audit_logs",
        ["tenant_id", "dossier_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "background_jobs",
        sa.Column("dossier_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("queue", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_background_jobs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_jobs")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_background_job_idempotency"),
    )
    op.create_index(
        "ix_background_jobs_tenant_status",
        "background_jobs",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("correction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_feedback_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_feedback_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_feedback_id_tenant"),
    )
    op.create_table(
        "score_history",
        sa.Column("dossier_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_score_history_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_history")),
    )
    op.create_index(
        "ix_score_history_resource",
        "score_history",
        ["tenant_id", "resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_name", sa.String(length=240), nullable=False),
        sa.Column("source_url", sa.String(length=1500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("credibility", sa.Integer(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credibility BETWEEN 0 AND 100", name=op.f("ck_signals_signal_credibility")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_signals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_signals_id_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "provider", "external_id", name="uq_signal_provider_external"
        ),
        sa.UniqueConstraint("tenant_id", "raw_hash", name="uq_signal_raw_hash"),
    )
    op.create_index(
        "ix_signals_tenant_published", "signals", ["tenant_id", "published_at"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("source_url", sa.String(length=1500), nullable=True),
        sa.Column("extract", sa.Text(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.LargeBinary(length=32), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('public','internal')",
            name=op.f("ck_evidence_evidence_classification"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id", "tenant_id"],
            ["signals.id", "signals.tenant_id"],
            name="fk_evidence_signal_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_evidence_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_evidence_id_tenant"),
    )
    op.create_table(
        "strategic_dossiers",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("dossier_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("strategic_goal", sa.Text(), nullable=False),
        sa.Column("geography", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sectors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("scoring_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("health_score", sa.Integer(), nullable=False),
        sa.Column("opportunity_score", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("score_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by_user_id", sa.UUID(), nullable=True),
        sa.Column("synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','paused','archived')",
            name=op.f("ck_strategic_dossiers_dossier_status"),
        ),
        sa.CheckConstraint(
            "health_score BETWEEN 0 AND 100 AND opportunity_score BETWEEN 0 AND 100 AND risk_score BETWEEN 0 AND 100",
            name=op.f("ck_strategic_dossiers_dossier_scores_range"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_strategic_dossiers_dossier_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["archived_by_user_id"],
            ["users.id"],
            name=op.f("fk_strategic_dossiers_archived_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_strategic_dossiers_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_strategic_dossiers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "tenant_id"],
            ["workspaces.id", "workspaces.tenant_id"],
            name="fk_dossiers_workspace_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategic_dossiers")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_strategic_dossiers_id_tenant"),
    )
    op.create_index(
        "ix_dossiers_tenant_owner",
        "strategic_dossiers",
        ["tenant_id", "owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_dossiers_tenant_status_updated",
        "strategic_dossiers",
        ["tenant_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "decisions",
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_decisions_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_decisions_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_decisions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_decisions_id_tenant"),
    )
    op.create_table(
        "dossier_actors",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("influence", sa.Integer(), nullable=False),
        sa.Column("relevance_to_dossier", sa.Integer(), nullable=False),
        sa.Column("relationship_strength", sa.Integer(), nullable=False),
        sa.Column("accessibility", sa.Integer(), nullable=False),
        sa.Column("strategic_alignment", sa.Integer(), nullable=False),
        sa.Column("recent_activity", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_dossier_actors_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_dossier_actors_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_dossier_actors_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dossier_actors")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_dossier_actors_id_tenant"),
        sa.UniqueConstraint("tenant_id", "dossier_id", "actor_id", name="uq_dossier_actor_link"),
    )
    op.create_table(
        "dossier_collaborators",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_dossier_collaborator_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dossier_collaborators_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "dossier_id", "user_id", name=op.f("pk_dossier_collaborators")
        ),
    )
    op.create_table(
        "dossier_objectives",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','achieved','cancelled')",
            name=op.f("ck_dossier_objectives_objective_status"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_objectives_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_dossier_objectives_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dossier_objectives")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_dossier_objectives_id_tenant"),
        sa.UniqueConstraint("tenant_id", "dossier_id", "position", name="uq_objective_position"),
    )
    op.create_table(
        "dossier_signals",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("novelty", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("strategic_impact", sa.Integer(), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("triage_version", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_resource_type", sa.String(length=30), nullable=True),
        sa.Column("promoted_resource_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new','reviewed','dismissed','promoted')",
            name=op.f("ck_dossier_signals_dossier_signal_status"),
        ),
        sa.CheckConstraint(
            "relevance BETWEEN 0 AND 100 AND novelty BETWEEN 0 AND 100 AND confidence BETWEEN 0 AND 100 AND strategic_impact BETWEEN 0 AND 100",
            name=op.f("ck_dossier_signals_dossier_signal_scores"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_dossier_signals_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_dossier_signals_reviewer_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id", "tenant_id"],
            ["signals.id", "signals.tenant_id"],
            name="fk_dossier_signals_signal_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_dossier_signals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dossier_signals")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_dossier_signals_id_tenant"),
        sa.UniqueConstraint("tenant_id", "dossier_id", "signal_id", name="uq_dossier_signal_link"),
    )
    op.create_index(
        "ix_dossier_signals_inbox",
        "dossier_signals",
        ["tenant_id", "dossier_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "hypotheses",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','supported','contradicted','discarded')",
            name=op.f("ck_hypotheses_hypothesis_status"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 100", name=op.f("ck_hypotheses_hypothesis_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_hypotheses_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_hypotheses_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypotheses")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_hypotheses_id_tenant"),
        sa.UniqueConstraint("tenant_id", "dossier_id", "position", name="uq_hypothesis_position"),
    )
    op.create_table(
        "insights",
        sa.Column("insight_type", sa.String(length=80), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("ai_audit_log_id", sa.UUID(), nullable=True),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_insights_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_insights_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_insights_id_tenant"),
    )
    op.create_table(
        "living_summaries",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_living_summary_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_living_summaries_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_living_summaries")),
        sa.UniqueConstraint("tenant_id", "dossier_id", name="uq_living_summary_dossier"),
    )
    op.create_table(
        "meetings",
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_meetings_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_meetings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_meetings_id_tenant"),
    )
    op.create_table(
        "opportunities",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("strategic_fit", sa.Integer(), nullable=False),
        sa.Column("urgency", sa.Integer(), nullable=False),
        sa.Column("expected_value", sa.Integer(), nullable=False),
        sa.Column("actionability", sa.Integer(), nullable=False),
        sa.Column("relationship_leverage", sa.Integer(), nullable=False),
        sa.Column("timing", sa.Integer(), nullable=False),
        sa.Column("effort", sa.Integer(), nullable=False),
        sa.Column("blocking_risk", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("source_dossier_signal_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("score_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_override", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "strategic_fit BETWEEN 0 AND 100 AND urgency BETWEEN 0 AND 100 AND expected_value BETWEEN 0 AND 100 AND actionability BETWEEN 0 AND 100 AND relationship_leverage BETWEEN 0 AND 100 AND timing BETWEEN 0 AND 100 AND confidence BETWEEN 0 AND 100 AND effort BETWEEN 0 AND 100 AND blocking_risk BETWEEN 0 AND 100 AND overall_score BETWEEN 0 AND 100",
            name=op.f("ck_opportunities_opportunity_scores"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_opportunities_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_opportunities_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_opportunities_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_opportunities_id_tenant"),
    )
    op.create_index(
        "ix_opportunities_tenant_dossier_status",
        "opportunities",
        ["tenant_id", "dossier_id", "status"],
        unique=False,
    )
    op.create_table(
        "relationships",
        sa.Column("from_actor_id", sa.UUID(), nullable=False),
        sa.Column("to_actor_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=True),
        sa.Column("relationship_type", sa.String(length=80), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_actor_id <> to_actor_id",
            name=op.f("ck_relationships_relationship_distinct_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_relationship_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_relationship_from_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_relationships_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_relationship_to_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_relationships_id_tenant"),
    )
    op.create_table(
        "reports",
        sa.Column("report_type", sa.String(length=80), nullable=False),
        sa.Column("template_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_reports_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
            name=op.f("fk_reports_generated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_reports_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_reports_id_tenant"),
    )
    op.create_table(
        "risk_items",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("likelihood", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("velocity", sa.Integer(), nullable=False),
        sa.Column("exposure", sa.Integer(), nullable=False),
        sa.Column("uncertainty", sa.Integer(), nullable=False),
        sa.Column("controllability", sa.Integer(), nullable=False),
        sa.Column("mitigation", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source_dossier_signal_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("score_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_override", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "likelihood BETWEEN 0 AND 100 AND impact BETWEEN 0 AND 100 AND velocity BETWEEN 0 AND 100 AND exposure BETWEEN 0 AND 100 AND uncertainty BETWEEN 0 AND 100 AND controllability BETWEEN 0 AND 100 AND confidence BETWEEN 0 AND 100 AND overall_score BETWEEN 0 AND 100",
            name=op.f("ck_risk_items_risk_scores"),
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_risks_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_risk_items_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_risk_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_items")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_risk_items_id_tenant"),
    )
    op.create_index(
        "ix_risks_tenant_dossier_status",
        "risk_items",
        ["tenant_id", "dossier_id", "status"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("linked_resource_type", sa.String(length=80), nullable=True),
        sa.Column("linked_resource_id", sa.UUID(), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_tasks_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tasks_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_tasks_id_tenant"),
    )
    op.create_index(
        "ix_tasks_tenant_owner_due",
        "tasks",
        ["tenant_id", "owner_user_id", "due_date"],
        unique=False,
    )
    op.create_table(
        "watchlists",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("query_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cadence", sa.String(length=50), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_watchlists_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_watchlists_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_watchlists_id_tenant"),
    )
    op.create_table(
        "briefings",
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id", "tenant_id"],
            ["meetings.id", "meetings.tenant_id"],
            name="fk_briefing_meeting_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_briefings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefings")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_briefings_id_tenant"),
    )
    op.create_table(
        "decision_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id", "tenant_id"],
            ["decisions.id", "decisions.tenant_id"],
            name="fk_decision_evidence_resource_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_decision_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "decision_id", "evidence_id", name=op.f("pk_decision_evidence")
        ),
    )
    op.create_table(
        "dossier_actor_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("dossier_actor_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_actor_id", "tenant_id"],
            ["dossier_actors.id", "dossier_actors.tenant_id"],
            name="fk_dossier_actor_evidence_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_dossier_actor_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "dossier_actor_id", "evidence_id", name=op.f("pk_dossier_actor_evidence")
        ),
    )
    op.create_table(
        "hypothesis_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("stance", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_hypothesis_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id", "tenant_id"],
            ["hypotheses.id", "hypotheses.tenant_id"],
            name="fk_hypothesis_evidence_hypothesis_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "hypothesis_id", "evidence_id", name=op.f("pk_hypothesis_evidence")
        ),
    )
    op.create_table(
        "insight_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("insight_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_insight_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["insight_id", "tenant_id"],
            ["insights.id", "insights.tenant_id"],
            name="fk_insight_evidence_resource_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "insight_id", "evidence_id", name=op.f("pk_insight_evidence")
        ),
    )
    op.create_table(
        "meeting_actors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_meeting_actor_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id", "tenant_id"],
            ["meetings.id", "meetings.tenant_id"],
            name="fk_meeting_actor_meeting_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "meeting_id", "actor_id", name=op.f("pk_meeting_actors")
        ),
    )
    op.create_table(
        "meeting_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_meeting_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id", "tenant_id"],
            ["meetings.id", "meetings.tenant_id"],
            name="fk_meeting_evidence_resource_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "meeting_id", "evidence_id", name=op.f("pk_meeting_evidence")
        ),
    )
    op.create_table(
        "opportunity_actors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_opportunity_actor_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id", "tenant_id"],
            ["opportunities.id", "opportunities.tenant_id"],
            name="fk_opportunity_actor_opportunity_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "opportunity_id", "actor_id", name=op.f("pk_opportunity_actors")
        ),
    )
    op.create_table(
        "opportunity_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_opportunity_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id", "tenant_id"],
            ["opportunities.id", "opportunities.tenant_id"],
            name="fk_opportunity_evidence_opportunity_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "opportunity_id", "evidence_id", name=op.f("pk_opportunity_evidence")
        ),
    )
    op.create_table(
        "opportunity_signals",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id", "tenant_id"],
            ["opportunities.id", "opportunities.tenant_id"],
            name="fk_opportunity_signal_opportunity_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id", "tenant_id"],
            ["signals.id", "signals.tenant_id"],
            name="fk_opportunity_signal_signal_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "opportunity_id", "signal_id", name=op.f("pk_opportunity_signals")
        ),
    )
    op.create_table(
        "relationship_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("relationship_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_relationship_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id", "tenant_id"],
            ["relationships.id", "relationships.tenant_id"],
            name="fk_relationship_evidence_relationship_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "relationship_id", "evidence_id", name=op.f("pk_relationship_evidence")
        ),
    )
    op.create_table(
        "report_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_report_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "tenant_id"],
            ["reports.id", "reports.tenant_id"],
            name="fk_report_evidence_resource_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "report_id", "evidence_id", name=op.f("pk_report_evidence")
        ),
    )
    op.create_table(
        "risk_actors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("risk_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id", "tenant_id"],
            ["actors.id", "actors.tenant_id"],
            name="fk_risk_actor_actor_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["risk_id", "tenant_id"],
            ["risk_items.id", "risk_items.tenant_id"],
            name="fk_risk_actor_risk_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "risk_id", "actor_id", name=op.f("pk_risk_actors")),
    )
    op.create_table(
        "risk_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("risk_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name="fk_risk_evidence_evidence_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["risk_id", "tenant_id"],
            ["risk_items.id", "risk_items.tenant_id"],
            name="fk_risk_evidence_risk_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "risk_id", "evidence_id", name=op.f("pk_risk_evidence")
        ),
    )
    op.create_table(
        "risk_signals",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("risk_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["risk_id", "tenant_id"],
            ["risk_items.id", "risk_items.tenant_id"],
            name="fk_risk_signal_risk_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id", "tenant_id"],
            ["signals.id", "signals.tenant_id"],
            name="fk_risk_signal_signal_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "risk_id", "signal_id", name=op.f("pk_risk_signals")),
    )
    op.create_table(
        "signal_monitors",
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cursor", sa.String(length=500), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_signal_monitors_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id", "tenant_id"],
            ["watchlists.id", "watchlists.tenant_id"],
            name="fk_monitors_watchlist_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_monitors")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_signal_monitors_id_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "provider", "external_id", name="uq_monitor_provider_external"
        ),
    )
    op.add_column("audit_events", sa.Column("dossier_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_audit_events_tenant_dossier_created",
        "audit_events",
        ["tenant_id", "dossier_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_audit_events_dossier_tenant",
        "audit_events",
        "strategic_dossiers",
        ["dossier_id", "tenant_id"],
        ["id", "tenant_id"],
        ondelete="RESTRICT",
    )
    tenant_tables = (
        "actors",
        "ai_audit_logs",
        "background_jobs",
        "feedback",
        "score_history",
        "signals",
        "evidence",
        "strategic_dossiers",
        "decisions",
        "dossier_actors",
        "dossier_collaborators",
        "dossier_objectives",
        "dossier_signals",
        "hypotheses",
        "insights",
        "living_summaries",
        "meetings",
        "opportunities",
        "relationships",
        "reports",
        "risk_items",
        "tasks",
        "watchlists",
        "briefings",
        "decision_evidence",
        "dossier_actor_evidence",
        "hypothesis_evidence",
        "insight_evidence",
        "meeting_actors",
        "meeting_evidence",
        "opportunity_actors",
        "opportunity_evidence",
        "opportunity_signals",
        "relationship_evidence",
        "report_evidence",
        "risk_actors",
        "risk_evidence",
        "risk_signals",
        "signal_monitors",
    )
    for table in tenant_tables:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" USING (tenant_id=oracle_current_tenant()) WITH CHECK (tenant_id=oracle_current_tenant())'
        )
    op.execute("""
      DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oracle_app') THEN
        GRANT SELECT,INSERT,UPDATE ON strategic_dossiers TO oracle_app;
        GRANT SELECT,INSERT,UPDATE,DELETE ON actors,ai_audit_logs,background_jobs,feedback,
          score_history,signals,evidence,decisions,dossier_actors,dossier_collaborators,
          dossier_objectives,dossier_signals,hypotheses,insights,living_summaries,meetings,
          opportunities,relationships,reports,risk_items,tasks,watchlists,briefings,
          decision_evidence,dossier_actor_evidence,hypothesis_evidence,insight_evidence,
          meeting_actors,meeting_evidence,opportunity_actors,opportunity_evidence,
          opportunity_signals,relationship_evidence,report_evidence,risk_actors,risk_evidence,
          risk_signals,signal_monitors TO oracle_app;
      END IF; END $$
    """)
    op.execute(
        "INSERT INTO role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.key FROM roles r CROSS JOIN permissions p WHERE r.key IN ('owner','admin') ON CONFLICT DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
      DELETE FROM role_permissions WHERE permission_key IN (
        'dossier.archive','signal.read','signal.promote','opportunity.read','opportunity.write',
        'risk.read','risk.write','actor.read','actor.write','meeting.read','meeting.write',
        'report.read','task.read','task.write'
      )
    """)
    op.execute("""
      DELETE FROM permissions WHERE key IN (
        'dossier.archive','signal.read','signal.promote','opportunity.read','opportunity.write',
        'risk.read','risk.write','actor.read','actor.write','meeting.read','meeting.write',
        'report.read','task.read','task.write'
      )
    """)
    op.drop_constraint("fk_audit_events_dossier_tenant", "audit_events", type_="foreignkey")
    op.drop_index("ix_audit_events_tenant_dossier_created", table_name="audit_events")
    op.drop_column("audit_events", "dossier_id")
    op.drop_table("signal_monitors")
    op.drop_table("risk_signals")
    op.drop_table("risk_evidence")
    op.drop_table("risk_actors")
    op.drop_table("report_evidence")
    op.drop_table("relationship_evidence")
    op.drop_table("opportunity_signals")
    op.drop_table("opportunity_evidence")
    op.drop_table("opportunity_actors")
    op.drop_table("meeting_evidence")
    op.drop_table("meeting_actors")
    op.drop_table("insight_evidence")
    op.drop_table("hypothesis_evidence")
    op.drop_table("dossier_actor_evidence")
    op.drop_table("decision_evidence")
    op.drop_table("briefings")
    op.drop_table("watchlists")
    op.drop_index("ix_tasks_tenant_owner_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_risks_tenant_dossier_status", table_name="risk_items")
    op.drop_table("risk_items")
    op.drop_table("reports")
    op.drop_table("relationships")
    op.drop_index("ix_opportunities_tenant_dossier_status", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("meetings")
    op.drop_table("living_summaries")
    op.drop_table("insights")
    op.drop_table("hypotheses")
    op.drop_index("ix_dossier_signals_inbox", table_name="dossier_signals")
    op.drop_table("dossier_signals")
    op.drop_table("dossier_objectives")
    op.drop_table("dossier_collaborators")
    op.drop_table("dossier_actors")
    op.drop_table("decisions")
    op.drop_index("ix_dossiers_tenant_status_updated", table_name="strategic_dossiers")
    op.drop_index("ix_dossiers_tenant_owner", table_name="strategic_dossiers")
    op.drop_table("strategic_dossiers")
    op.drop_table("evidence")
    op.drop_index("ix_signals_tenant_published", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_score_history_resource", table_name="score_history")
    op.drop_table("score_history")
    op.drop_table("feedback")
    op.drop_index("ix_background_jobs_tenant_status", table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index("ix_ai_audit_tenant_dossier", table_name="ai_audit_logs")
    op.drop_table("ai_audit_logs")
    op.drop_index("ix_actors_tenant_name", table_name="actors")
    op.drop_table("actors")
    op.drop_constraint("uq_workspaces_id_tenant", "workspaces", type_="unique")
    # ### end Alembic commands ###
