"""documents evidence search

Revision ID: 20260711_0009
Revises: 20260710_0008
Create Date: 2026-07-11 01:01:21.913573
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260711_0009"
down_revision: str | None = "20260710_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_retention_policies",
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("purge_grace_days", sa.Integer(), nullable=False),
        sa.Column("preserve_metadata", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "retention_days >= 1 AND purge_grace_days >= 0",
            name=op.f("ck_document_retention_policies_document_retention_days"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_retention_policies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_retention_policies")),
        sa.UniqueConstraint("tenant_id", name="uq_document_retention_tenant"),
    )
    op.create_table(
        "documents",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=600), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.LargeBinary(length=32), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scan_status", sa.String(length=30), nullable=False),
        sa.Column("scan_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status='deleted') = (deleted_at IS NOT NULL)",
            name=op.f("ck_documents_document_deleted_state"),
        ),
        sa.CheckConstraint(
            "classification IN ('public','internal')",
            name=op.f("ck_documents_document_classification"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(scan_result)='object' AND jsonb_typeof(metadata)='object'",
            name=op.f("ck_documents_document_json_objects"),
        ),
        sa.CheckConstraint(
            "scan_status IN ('pending','clean','infected','error','not_configured')",
            name=op.f("ck_documents_document_scan_status"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','queued','processing','ready','failed','quarantined','deleted')",
            name=op.f("ck_documents_document_status"),
        ),
        sa.CheckConstraint(
            "octet_length(checksum)=32 AND length(storage_key) BETWEEN 1 AND 600",
            name=op.f("ck_documents_document_storage_integrity"),
        ),
        sa.CheckConstraint(
            "version >= 1 AND byte_size >= 0", name=op.f("ck_documents_document_version_size")
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            name="fk_documents_dossier_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "deleted_by_user_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.user_id"],
            name="fk_documents_deleter_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "uploaded_by_user_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.user_id"],
            name="fk_documents_uploader_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_documents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("id", "dossier_id", "tenant_id", name="uq_documents_context"),
        sa.UniqueConstraint("id", "tenant_id", name="uq_documents_id_tenant"),
        sa.UniqueConstraint("tenant_id", "storage_key", name="uq_documents_tenant_storage_key"),
    )
    op.create_index(
        "ix_documents_dossier_status",
        "documents",
        ["tenant_id", "dossier_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_documents_retention",
        "documents",
        ["tenant_id", "deleted_at", "purge_after"],
        unique=False,
    )
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("parser_name", sa.String(length=80), nullable=True),
        sa.Column("parser_version", sa.String(length=40), nullable=True),
        sa.Column("chunker_version", sa.String(length=40), nullable=True),
        sa.Column("source_checksum", sa.LargeBinary(length=32), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("processing_token", sa.UUID(), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(provenance)='object'",
            name=op.f("ck_document_versions_document_version_provenance"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','scanning','processing','ready','failed','quarantined','superseded','purged')",
            name=op.f("ck_document_versions_document_version_status"),
        ),
        sa.CheckConstraint(
            "octet_length(source_checksum)=32",
            name=op.f("ck_document_versions_document_version_checksum"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_document_versions_document_version_number")
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "dossier_id", "tenant_id"],
            ["documents.id", "documents.dossier_id", "documents.tenant_id"],
            name="fk_document_versions_document_context",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_versions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("id", "document_id", "tenant_id", name="uq_document_versions_context"),
        sa.UniqueConstraint("id", "tenant_id", name="uq_document_versions_id_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "document_id", "version_number", name="uq_document_version_no"
        ),
    )
    op.create_index(
        "ix_document_versions_document",
        "document_versions",
        ["tenant_id", "document_id", "version_number"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_documents_current_version_context",
        "documents",
        "document_versions",
        ["current_version_id", "id", "tenant_id"],
        ["id", "document_id", "tenant_id"],
    )
    op.create_table(
        "document_chunks",
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("paragraph_number", sa.Integer(), nullable=True),
        sa.Column("time_start_ms", sa.Integer(), nullable=True),
        sa.Column("time_end_ms", sa.Integer(), nullable=True),
        sa.Column("speaker", sa.String(length=160), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.LargeBinary(length=32), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', coalesce(text_content, ''))", persisted=True),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(locator)='object' AND jsonb_typeof(provenance)='object'",
            name=op.f("ck_document_chunks_document_chunk_json_objects"),
        ),
        sa.CheckConstraint(
            "octet_length(checksum)=32", name=op.f("ck_document_chunks_document_chunk_checksum")
        ),
        sa.CheckConstraint(
            "sequence >= 0 AND char_start >= 0 AND char_end > char_start",
            name=op.f("ck_document_chunks_document_chunk_offsets"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "dossier_id", "tenant_id"],
            ["documents.id", "documents.dossier_id", "documents.tenant_id"],
            name="fk_document_chunks_document_context",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id", "document_id", "tenant_id"],
            [
                "document_versions.id",
                "document_versions.document_id",
                "document_versions.tenant_id",
            ],
            name="fk_document_chunks_version_context",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_chunks_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "id", "document_version_id", "tenant_id", name="uq_document_chunks_context"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_document_chunks_id_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "document_version_id", "sequence", name="uq_document_chunk_sequence"
        ),
    )
    op.create_index(
        "ix_document_chunks_dossier",
        "document_chunks",
        ["tenant_id", "dossier_id", "document_id", "sequence"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_search",
        "document_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "document_processing_attempts",
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("background_job_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("execution_token", sa.UUID(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('reserved','scanning','parsing','chunking','succeeded','failed','abandoned')",
            name=op.f("ck_document_processing_attempts_document_attempt_status"),
        ),
        sa.CheckConstraint(
            "attempt_number >= 1",
            name=op.f("ck_document_processing_attempts_document_attempt_number"),
        ),
        sa.ForeignKeyConstraint(
            ["background_job_id", "tenant_id"],
            ["background_jobs.id", "background_jobs.tenant_id"],
            name="fk_document_attempt_job_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id", "tenant_id"],
            ["document_versions.id", "document_versions.tenant_id"],
            name="fk_document_attempt_version_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_processing_attempts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_processing_attempts")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_document_attempts_id_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "document_version_id", "attempt_number", name="uq_document_attempt_no"
        ),
    )
    op.create_index(
        "ix_document_attempt_lease",
        "document_processing_attempts",
        ["tenant_id", "status", "lease_expires_at"],
        unique=False,
    )
    op.add_column("evidence", sa.Column("document_version_id", sa.UUID(), nullable=True))
    op.add_column("evidence", sa.Column("document_chunk_id", sa.UUID(), nullable=True))
    op.add_column("evidence", sa.Column("source_kind", sa.String(length=30), nullable=True))
    op.execute("""
      UPDATE evidence SET
        provenance = provenance || jsonb_build_object(
          'migration_status','quarantined_missing_source',
          'legacy_document_id',CASE
            WHEN provenance ? 'legacy_document_id' THEN provenance->'legacy_document_id'
            WHEN document_id IS NULL THEN 'null'::jsonb
            ELSE to_jsonb(document_id::text)
          END
        ),
        document_id = NULL,
        source_kind = CASE WHEN signal_id IS NOT NULL THEN 'signal' ELSE 'legacy_unresolved' END
      WHERE document_id IS NOT NULL OR signal_id IS NULL
    """)
    op.execute("UPDATE evidence SET source_kind='signal' WHERE source_kind IS NULL")
    op.alter_column("evidence", "source_kind", nullable=False)
    op.create_foreign_key(
        "fk_evidence_document_version_context",
        "evidence",
        "document_versions",
        ["document_version_id", "document_id", "tenant_id"],
        ["id", "document_id", "tenant_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_evidence_document_chunk_context",
        "evidence",
        "document_chunks",
        ["document_chunk_id", "document_version_id", "tenant_id"],
        ["id", "document_version_id", "tenant_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_evidence_document_tenant",
        "evidence",
        "documents",
        ["document_id", "tenant_id"],
        ["id", "tenant_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "evidence_source_shape",
        "evidence",
        "(source_kind='signal' AND signal_id IS NOT NULL AND document_id IS NULL "
        "AND document_version_id IS NULL AND document_chunk_id IS NULL) OR "
        "(source_kind='document' AND signal_id IS NULL AND document_id IS NOT NULL "
        "AND document_version_id IS NOT NULL AND document_chunk_id IS NOT NULL) OR "
        "(source_kind='legacy_unresolved' AND signal_id IS NULL AND document_id IS NULL "
        "AND document_version_id IS NULL AND document_chunk_id IS NULL "
        'AND provenance @> \'{"migration_status":"quarantined_missing_source"}\'::jsonb)',
    )
    tenant_tables = (
        "documents",
        "document_versions",
        "document_chunks",
        "document_processing_attempts",
        "document_retention_policies",
    )
    for table in tenant_tables:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" USING '
            "(tenant_id=oracle_current_tenant()) WITH CHECK "
            "(tenant_id=oracle_current_tenant())"
        )
    op.execute("""
      DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oracle_app') THEN
        GRANT SELECT,INSERT,UPDATE,DELETE ON documents,document_versions,document_chunks,
          document_processing_attempts,document_retention_policies TO oracle_app;
      END IF; END $$
    """)
    op.execute("""
      INSERT INTO permissions(key,description) VALUES
        ('documents.read','Consultar documentos y evidencias'),
        ('documents.manage','Subir, reprocesar y retirar documentos')
      ON CONFLICT (key) DO NOTHING
    """)
    op.execute("""
      INSERT INTO role_permissions(tenant_id,role_id,permission_key)
      SELECT r.tenant_id,r.id,p.key FROM roles r JOIN permissions p
        ON p.key IN ('documents.read','documents.manage')
      WHERE r.key IN ('owner','admin','analyst')
      ON CONFLICT DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM role_permissions WHERE permission_key IN ('documents.read','documents.manage')"
    )
    op.execute("DELETE FROM permissions WHERE key IN ('documents.read','documents.manage')")
    op.drop_constraint("evidence_source_shape", "evidence", type_="check")
    op.drop_constraint("fk_evidence_document_tenant", "evidence", type_="foreignkey")
    op.drop_constraint("fk_evidence_document_chunk_context", "evidence", type_="foreignkey")
    op.drop_constraint("fk_evidence_document_version_context", "evidence", type_="foreignkey")
    op.drop_column("evidence", "document_chunk_id")
    op.drop_column("evidence", "document_version_id")
    op.drop_column("evidence", "source_kind")
    op.drop_index("ix_document_attempt_lease", table_name="document_processing_attempts")
    op.drop_table("document_processing_attempts")
    op.drop_index("ix_document_chunks_search", table_name="document_chunks", postgresql_using="gin")
    op.drop_index("ix_document_chunks_dossier", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_document_versions_document", table_name="document_versions")
    op.drop_constraint("fk_documents_current_version_context", "documents", type_="foreignkey")
    op.drop_table("document_versions")
    op.drop_index("ix_documents_retention", table_name="documents")
    op.drop_index("ix_documents_dossier_status", table_name="documents")
    op.drop_table("documents")
    op.drop_table("document_retention_policies")
    # ### end Alembic commands ###
