"""AI runtime audit artifacts policies and usage

Revision ID: 20260710_0008
Revises: 20260710_0007
Create Date: 2026-07-11 00:09:26.005504
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260710_0008"
down_revision: str | None = "20260710_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_tenant_policies",
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("allowed_models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_classification", sa.String(length=30), nullable=False),
        sa.Column("monthly_soft_budget_micros", sa.Integer(), nullable=False),
        sa.Column("monthly_hard_budget_micros", sa.Integer(), nullable=False),
        sa.Column("daily_call_limit", sa.Integer(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("max_context_tokens", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("kill_switch", sa.Boolean(), nullable=False),
        sa.Column("redaction_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_concurrency >= 1", name=op.f("ck_ai_tenant_policies_ai_policy_concurrency")
        ),
        sa.CheckConstraint(
            "provider IN ('disabled','mock')", name=op.f("ck_ai_tenant_policies_ai_policy_provider")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(allowed_models)='array'",
            name=op.f("ck_ai_tenant_policies_ai_policy_models"),
        ),
        sa.CheckConstraint(
            "max_classification IN ('public','internal')",
            name=op.f("ck_ai_tenant_policies_ai_policy_classification"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(redaction_profile)='object'",
            name=op.f("ck_ai_tenant_policies_ai_policy_redaction"),
        ),
        sa.CheckConstraint(
            "monthly_soft_budget_micros >= 0 AND monthly_hard_budget_micros >= 0 "
            "AND (monthly_hard_budget_micros = 0 OR monthly_soft_budget_micros <= monthly_hard_budget_micros) "
            "AND daily_call_limit >= 0 AND max_context_tokens >= 1 AND max_output_tokens >= 1",
            name=op.f("ck_ai_tenant_policies_ai_policy_limits"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_tenant_policies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_tenant_policies")),
        sa.UniqueConstraint("tenant_id", name="uq_ai_policy_tenant"),
    )
    op.create_table(
        "ai_artifacts",
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("agent", sa.String(length=100), nullable=False),
        sa.Column("schema_name", sa.String(length=150), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(output)='object'", name=op.f("ck_ai_artifacts_ai_artifact_output_object")
        ),
        sa.CheckConstraint(
            "status IN ('candidate','valid','rejected','superseded')",
            name=op.f("ck_ai_artifacts_ai_artifact_status"),
        ),
        sa.CheckConstraint(
            "octet_length(output_hash)=32", name=op.f("ck_ai_artifacts_ai_artifact_output_hash")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ai_artifacts_ai_artifact_version")),
        sa.ForeignKeyConstraint(
            ["audit_log_id", "tenant_id"],
            ["ai_audit_logs.id", "ai_audit_logs.tenant_id"],
            name=op.f("fk_ai_artifacts_audit_log_id_ai_audit_logs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_artifacts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_artifacts")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_ai_artifacts_id_tenant"),
        sa.UniqueConstraint("tenant_id", "audit_log_id", name="uq_ai_artifact_audit"),
    )
    op.create_index(
        "ix_ai_artifact_target",
        "ai_artifacts",
        ["tenant_id", "target_type", "target_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_attempts",
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("request_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("response_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_micros", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_token", sa.UUID(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_number >= 1", name=op.f("ck_ai_attempts_ai_attempt_number")),
        sa.CheckConstraint(
            "octet_length(request_hash)=32", name=op.f("ck_ai_attempts_ai_attempt_request_hash")
        ),
        sa.CheckConstraint(
            "response_hash IS NULL OR octet_length(response_hash)=32",
            name=op.f("ck_ai_attempts_ai_attempt_response_hash"),
        ),
        sa.CheckConstraint(
            "kind IN ('generate','repair','reviewer')", name=op.f("ck_ai_attempts_ai_attempt_kind")
        ),
        sa.CheckConstraint(
            "status IN ('reserved','running','succeeded','failed','abandoned')",
            name=op.f("ck_ai_attempts_ai_attempt_status"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cost_micros >= 0 AND (latency_ms IS NULL OR latency_ms >= 0)",
            name=op.f("ck_ai_attempts_ai_attempt_metrics"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_log_id", "tenant_id"],
            ["ai_audit_logs.id", "ai_audit_logs.tenant_id"],
            name=op.f("fk_ai_attempts_audit_log_id_ai_audit_logs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_attempts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_attempts")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_ai_attempts_id_tenant"),
        sa.UniqueConstraint("tenant_id", "audit_log_id", "attempt_number", name="uq_ai_attempt_no"),
    )
    op.create_table(
        "ai_context_snapshots",
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("context_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("source_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("redaction_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("injection_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_manifest)='object'",
            name=op.f("ck_ai_context_snapshots_ai_context_manifest"),
        ),
        sa.CheckConstraint(
            "octet_length(context_hash)=32", name=op.f("ck_ai_context_snapshots_ai_context_hash")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(redaction_summary)='object'",
            name=op.f("ck_ai_context_snapshots_ai_context_redaction"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(injection_indicators)='array'",
            name=op.f("ck_ai_context_snapshots_ai_context_injection_indicators"),
        ),
        sa.CheckConstraint(
            "classification IN ('public','internal')",
            name=op.f("ck_ai_context_snapshots_ai_context_classification"),
        ),
        sa.CheckConstraint(
            "estimated_tokens >= 0",
            name=op.f("ck_ai_context_snapshots_ai_context_estimated_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_log_id", "tenant_id"],
            ["ai_audit_logs.id", "ai_audit_logs.tenant_id"],
            name=op.f("fk_ai_context_snapshots_audit_log_id_ai_audit_logs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id", "tenant_id"],
            ["strategic_dossiers.id", "strategic_dossiers.tenant_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_context_snapshots_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_context_snapshots")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_ai_context_id_tenant"),
        sa.UniqueConstraint("tenant_id", "audit_log_id", name="uq_ai_context_audit"),
    )
    op.create_table(
        "ai_usage_ledger",
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=150), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("reserved_cost_micros", sa.Integer(), nullable=False),
        sa.Column("actual_cost_micros", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("execution_token", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reserved_cost_micros >= 0 AND actual_cost_micros >= 0",
            name=op.f("ck_ai_usage_ledger_ai_usage_cost"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name=op.f("ck_ai_usage_ledger_ai_usage_tokens"),
        ),
        sa.CheckConstraint(
            "period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'", name=op.f("ck_ai_usage_ledger_ai_usage_period")
        ),
        sa.CheckConstraint(
            "status IN ('reserved','settled','released')",
            name=op.f("ck_ai_usage_ledger_ai_usage_status"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_log_id", "tenant_id"],
            ["ai_audit_logs.id", "ai_audit_logs.tenant_id"],
            name=op.f("fk_ai_usage_ledger_audit_log_id_ai_audit_logs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_usage_ledger_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_ledger")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_ai_usage_id_tenant"),
        sa.UniqueConstraint("tenant_id", "audit_log_id", name="uq_ai_usage_audit"),
    )
    op.create_index(
        "ix_ai_usage_period", "ai_usage_ledger", ["tenant_id", "period", "created_at"], unique=False
    )
    op.create_table(
        "ai_context_evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("evidence_hash", sa.LargeBinary(length=32), nullable=False),
        sa.CheckConstraint(
            "octet_length(evidence_hash)=32",
            name=op.f("ck_ai_context_evidence_ai_context_evidence_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "tenant_id"],
            ["evidence.id", "evidence.tenant_id"],
            name=op.f("fk_ai_context_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "tenant_id"],
            ["ai_context_snapshots.id", "ai_context_snapshots.tenant_id"],
            name=op.f("fk_ai_context_evidence_snapshot_id_ai_context_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "evidence_id", "dossier_id"],
            [
                "evidence_dossiers.tenant_id",
                "evidence_dossiers.evidence_id",
                "evidence_dossiers.dossier_id",
            ],
            name=op.f("fk_ai_context_evidence_tenant_id_evidence_dossiers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "snapshot_id", "evidence_id", name=op.f("pk_ai_context_evidence")
        ),
    )
    op.create_table(
        "ai_human_reviews",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("override", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('accepted','rejected','changes_requested')",
            name=op.f("ck_ai_human_reviews_ai_review_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(override)='object'", name=op.f("ck_ai_human_reviews_ai_review_override")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "tenant_id"],
            ["ai_artifacts.id", "ai_artifacts.tenant_id"],
            name=op.f("fk_ai_human_reviews_artifact_id_ai_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reviewer_user_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.user_id"],
            name=op.f("fk_ai_human_reviews_tenant_id_tenant_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_human_reviews_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_human_reviews")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_ai_reviews_id_tenant"),
    )
    op.add_column("ai_audit_logs", sa.Column("background_job_id", sa.UUID(), nullable=True))
    op.add_column("ai_audit_logs", sa.Column("requested_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "ai_audit_logs",
        sa.Column("agent", sa.String(length=100), server_default="unknown", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("action", sa.String(length=100), server_default="generate", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column(
            "prompt_hash",
            sa.LargeBinary(length=32),
            server_default=sa.text("decode(repeat('00',32),'hex')"),
            nullable=False,
        ),
    )
    op.add_column(
        "ai_audit_logs", sa.Column("context_hash", sa.LargeBinary(length=32), nullable=True)
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("schema_name", sa.String(length=150), server_default="unknown", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("schema_version", sa.String(length=50), server_default="v1", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column(
            "data_classification", sa.String(length=30), server_default="internal", nullable=False
        ),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("redaction_applied", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column(
            "redaction_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "ai_audit_logs", sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("actual_cost_micros", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column("currency", sa.String(length=3), server_default="EUR", nullable=False),
    )
    op.add_column("ai_audit_logs", sa.Column("error_code", sa.String(length=100), nullable=True))
    op.add_column(
        "ai_audit_logs",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "ai_audit_logs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "ai_audit_logs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "ai_audit_logs",
        sa.Column(
            "human_review_state",
            sa.String(length=30),
            server_default="not_required",
            nullable=False,
        ),
    )
    op.create_index(
        "ix_ai_audit_tenant_status",
        "ai_audit_logs",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_ai_audit_job_agent",
        "ai_audit_logs",
        ["tenant_id", "background_job_id", "agent"],
    )
    op.create_foreign_key(
        "fk_ai_audit_background_job_tenant",
        "ai_audit_logs",
        "background_jobs",
        ["background_job_id", "tenant_id"],
        ["id", "tenant_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_ai_audit_requester_membership",
        "ai_audit_logs",
        "tenant_memberships",
        ["tenant_id", "requested_by_user_id"],
        ["tenant_id", "user_id"],
        ondelete="RESTRICT",
    )
    op.execute(
        """
        UPDATE ai_audit_logs
        SET input_hash = CASE WHEN octet_length(input_hash) = 32 THEN input_hash
            ELSE decode(repeat('00',32),'hex') END,
            output_hash = CASE WHEN output_hash IS NULL OR octet_length(output_hash) = 32
            THEN output_hash ELSE NULL END
        """
    )
    op.create_check_constraint(
        "ai_audit_prompt_hash", "ai_audit_logs", "octet_length(prompt_hash)=32"
    )
    op.create_check_constraint(
        "ai_audit_input_hash", "ai_audit_logs", "octet_length(input_hash)=32"
    )
    op.create_check_constraint(
        "ai_audit_output_hash",
        "ai_audit_logs",
        "output_hash IS NULL OR octet_length(output_hash)=32",
    )
    op.execute(
        """
        UPDATE ai_audit_logs
        SET status = CASE
            WHEN status = 'completed' THEN 'succeeded'
            WHEN status IN ('pending','running','succeeded','failed','denied') THEN status
            ELSE 'failed'
        END,
        input_hash = CASE WHEN octet_length(input_hash) = 32 THEN input_hash
            ELSE decode(repeat('00',32),'hex') END,
        output_hash = CASE WHEN output_hash IS NULL OR octet_length(output_hash) = 32
            THEN output_hash ELSE NULL END,
        latency_ms = CASE WHEN latency_ms IS NULL THEN NULL ELSE GREATEST(latency_ms, 0) END,
        estimated_cost_micros = CASE WHEN estimated_cost_micros IS NULL THEN NULL
            ELSE GREATEST(estimated_cost_micros, 0) END
        """
    )
    op.create_check_constraint(
        "ai_audit_status",
        "ai_audit_logs",
        "status IN ('pending','running','succeeded','failed','denied')",
    )
    op.create_check_constraint(
        "ai_audit_review_state",
        "ai_audit_logs",
        "human_review_state IN ('not_required','pending','accepted','rejected','changes_requested')",
    )
    op.create_check_constraint(
        "ai_audit_classification", "ai_audit_logs", "data_classification IN ('public','internal')"
    )
    op.create_check_constraint(
        "ai_audit_redaction", "ai_audit_logs", "jsonb_typeof(redaction_summary)='object'"
    )
    op.create_check_constraint(
        "ai_audit_metrics",
        "ai_audit_logs",
        "input_tokens >= 0 AND output_tokens >= 0 AND actual_cost_micros >= 0 "
        "AND attempt_count >= 0 AND (latency_ms IS NULL OR latency_ms >= 0) "
        "AND (estimated_cost_micros IS NULL OR estimated_cost_micros >= 0)",
    )
    for column in (
        "agent",
        "action",
        "prompt_hash",
        "schema_name",
        "schema_version",
        "data_classification",
        "redaction_applied",
        "redaction_summary",
        "input_tokens",
        "output_tokens",
        "actual_cost_micros",
        "currency",
        "attempt_count",
        "human_review_state",
    ):
        op.alter_column("ai_audit_logs", column, server_default=None)
    tenant_tables = (
        "ai_tenant_policies",
        "ai_artifacts",
        "ai_attempts",
        "ai_context_snapshots",
        "ai_usage_ledger",
        "ai_context_evidence",
        "ai_human_reviews",
    )
    for table in tenant_tables:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" USING '
            "(tenant_id=oracle_current_tenant()) WITH CHECK "
            "(tenant_id=oracle_current_tenant())"
        )
    op.execute("""
      DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oracle_app') THEN
        GRANT SELECT,INSERT,UPDATE,DELETE ON ai_tenant_policies,ai_artifacts,ai_attempts,
          ai_context_snapshots,ai_usage_ledger,ai_context_evidence,ai_human_reviews TO oracle_app;
      END IF; END $$
    """)
    op.execute("""
      INSERT INTO permissions(key,description) VALUES
        ('ai.execute','Ejecutar análisis IA'),
        ('ai.review','Revisar resultados IA')
      ON CONFLICT (key) DO NOTHING
    """)
    op.execute("""
      INSERT INTO role_permissions(tenant_id,role_id,permission_key)
      SELECT r.tenant_id,r.id,p.key FROM roles r JOIN permissions p
        ON p.key IN ('ai.execute','ai.review') WHERE r.key IN ('owner','admin')
      ON CONFLICT DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role_permissions WHERE permission_key IN ('ai.execute','ai.review')")
    op.execute("DELETE FROM permissions WHERE key IN ('ai.execute','ai.review')")
    op.execute(
        "ALTER TABLE ai_audit_logs "
        "DROP CONSTRAINT IF EXISTS ai_audit_metrics, "
        "DROP CONSTRAINT IF EXISTS ck_ai_audit_logs_ai_audit_metrics, "
        "DROP CONSTRAINT IF EXISTS ai_audit_redaction, "
        "DROP CONSTRAINT IF EXISTS ck_ai_audit_logs_ai_audit_redaction, "
        "DROP CONSTRAINT IF EXISTS ai_audit_classification, "
        "DROP CONSTRAINT IF EXISTS ck_ai_audit_logs_ai_audit_classification"
    )
    for constraint in (
        "ai_audit_review_state",
        "ai_audit_status",
        "ai_audit_output_hash",
        "ai_audit_input_hash",
        "ai_audit_prompt_hash",
    ):
        op.drop_constraint(constraint, "ai_audit_logs", type_="check")
    op.drop_constraint("fk_ai_audit_requester_membership", "ai_audit_logs", type_="foreignkey")
    op.drop_constraint("fk_ai_audit_background_job_tenant", "ai_audit_logs", type_="foreignkey")
    op.drop_index("ix_ai_audit_tenant_status", table_name="ai_audit_logs")
    op.drop_constraint("uq_ai_audit_job_agent", "ai_audit_logs", type_="unique")
    op.drop_column("ai_audit_logs", "human_review_state")
    op.drop_column("ai_audit_logs", "completed_at")
    op.drop_column("ai_audit_logs", "started_at")
    op.drop_column("ai_audit_logs", "attempt_count")
    op.drop_column("ai_audit_logs", "error_code")
    op.drop_column("ai_audit_logs", "currency")
    op.drop_column("ai_audit_logs", "actual_cost_micros")
    op.drop_column("ai_audit_logs", "output_tokens")
    op.drop_column("ai_audit_logs", "input_tokens")
    op.drop_column("ai_audit_logs", "redaction_summary")
    op.drop_column("ai_audit_logs", "redaction_applied")
    op.drop_column("ai_audit_logs", "data_classification")
    op.drop_column("ai_audit_logs", "schema_version")
    op.drop_column("ai_audit_logs", "schema_name")
    op.drop_column("ai_audit_logs", "context_hash")
    op.drop_column("ai_audit_logs", "prompt_hash")
    op.drop_column("ai_audit_logs", "action")
    op.drop_column("ai_audit_logs", "agent")
    op.drop_column("ai_audit_logs", "requested_by_user_id")
    op.drop_column("ai_audit_logs", "background_job_id")
    op.drop_table("ai_human_reviews")
    op.drop_table("ai_context_evidence")
    op.drop_index("ix_ai_usage_period", table_name="ai_usage_ledger")
    op.drop_table("ai_usage_ledger")
    op.drop_table("ai_context_snapshots")
    op.drop_table("ai_attempts")
    op.drop_index("ix_ai_artifact_target", table_name="ai_artifacts")
    op.drop_table("ai_artifacts")
    op.drop_table("ai_tenant_policies")
    # ### end Alembic commands ###
