bind 0.0.0.0 ::0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300

databases 16
dir /data
dbfilename dump.rdb
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
aof-use-rdb-preamble yes
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

maxmemory 256mb
maxmemory-policy noeviction
maxmemory-samples 5

loglevel notice
logfile ""
always-show-logo no
supervised no
